#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=LEfSe
#SBATCH --error=../../Script_Output/Dataset1_Output/ErrorOut/LEfSe.err
#SBATCH --output=../../Script_Output/Dataset1_Output/Output/LEfSe.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=16000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

#Enable the 'conda' command and load LEfSe conda environment
. /home/wallenz/miniconda3/etc/profile.d/conda.sh
conda activate lefse

R CMD BATCH LEfSe.R ../../Script_Output/Dataset1_Output/Output/LEfSe.Rout

