#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=Plotting
#SBATCH --error=../Script_Output/Joint_Analyses_Output/ErrorOut/Plotting.err
#SBATCH --output=../Script_Output/Joint_Analyses_Output/Output/Plotting.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=16000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

module load R
module unload R

Rscript Plotting.R
